container:
  image: kronicdeth/lumen-development:latest
  cpu: 4
  memory: 12

x86_64_test_task:
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  build_script: cargo build
  test_script: cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index

wasm32_test_task:
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  lumen_web_test_script: |
    pushd lumen_web
    wasm-pack test --headless --chrome
    popd
  examples_spawn_chain_test_script: |
    pushd examples/spawn-chain
    wasm-pack test --headless --chrome
    popd
  before_cache_script: rm -rf $CARGO_HOME/registry/index

