[workspace]

members = [
  "lumen",
  "lumen_runtime",
  "liblumen_arena",
  "liblumen_alloc",
  "liblumen_beam",
  "liblumen_codegen",
  "liblumen_common",
  "liblumen_compiler",
  "liblumen_core",
  "liblumen_diagnostics",
  "liblumen_syntax",
]
