[package]
name = "liblumen_core"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
failure = "0.1"
liblumen_common = { path = "../liblumen_common" }
liblumen_syntax = { path = "../liblumen_syntax" }
