[package]
name = "liblumen_alloc"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
cfg-if = "0.1"
lazy_static = "1.2"
liblumen_core = { path = "../liblumen_core" }
liblumen_alloc_macros = { path = "../liblumen_alloc_macros" }

[dependencies.bitvec]
git = "https://github.com/bitwalker/bitvec"
default-features = false
features = ["alloc"]

[dependencies.intrusive-collections]
version = "0.7"
features = ["nightly"]

[dependencies.num-traits]
version = "0.2"
default-features = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

[dev-dependencies]
quickcheck_macros = "0.8"

[dev-dependencies.quickcheck]
version = "0.8"
features = ["unstable"]