[package]
name = "liblumen_alloc"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
log = "0.4"
cfg-if = "0.1"
lazy_static = "1.2"
num-traits = "0.2"
num-bigint = "0.2"
thread_local = "0.3"
liblumen_core = { path = "../liblumen_core" }
liblumen_arena = { path = "../liblumen_arena"}
liblumen_alloc_macros = { path = "../liblumen_alloc_macros" }

[dependencies.hashbrown]
version = "0.5"
git = "https://github.com/KronicDeth/hashbrown.git"
branch = "E0658"
features = ["nightly"]

[dependencies.intrusive-collections]
version = "0.7"
features = ["nightly"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

[dev-dependencies]
pretty_assertions = "0.6"
quickcheck_macros = "0.8"

[dev-dependencies.quickcheck]
version = "0.8"
features = ["unstable"]
